### ISSUE TITLE
Add yahoo Finances as Exchange Rate implementation

### ISSUE THREAD

**Issue by otaviojava** [JavaMoney/javamoney-lib#22]
Add yahoo Finances as Exchange Rate implementation

**Comment by keilw** [comment]
Sounds good, this explains the YQL for Finance (and other sources on the bottom) http://stackoverflow.com/questions/10040954/alternative-to-google-finance-api

**Comment by kosik** [comment]
https://github.com/kosik/jsr354-ri catch one eye here

**Comment by keilw** [comment]
Thanks, but it should not go to RI;-(

**Comment by keilw** [comment]
Sorry for the possible confusion (e.g. the Moneta module @otaviojava cloned here likely will be a module, but to have default providers IMF and ECB should stay as modules under Moneta;-) 
We may manually transfer the suggested file changes from your pull-request, or you could place it here instead under "exchange-rate", I can later create a module once I am at my own box.

**Comment by kosik** [comment]
The second attempt pushed into javamoney-lib.

To be honest i implement it for my local project necessity. It went out that it will be much faster, easer and safer to implement the Parser than use a third-party service or invent something by myself. So, thank you guys for the work :) I have not done any Test Development Cases. I just did some smoke tests and it was enough for me. 

By the way, according to one of Stackoverflow posts YAHOO does not provide official support of exchange rate currencies. It seems like the currencies are available only as a part of Yahoo Finances but not like the independent web-service.

**Comment by otaviojava** [comment]
Ok.
I can continue your code and the tests.
I will use your code as first step, thank you.

**Comment by keilw** [comment]
Which code, the one from the RI PR? As long as it's not merged there (here no problem, as this is not subject to EG/JCP membership ;-) fine. I just created a structure of a sub-module https://github.com/JavaMoney/javamoney-lib/tree/master/exchange-rate/exchange-rate-yho

**Comment by otaviojava** [comment]
I will create the structure on lib

**Comment by keilw** [comment]
The folder is there, but happy if you fill it (both of you unless you prefer to manually carry over the proposed PR, please don't use javamoney.moneta package name. Either "org.javamoney.lib.exchange.*" or (since a few other modules like "calc" also did) "org.javamoney.exchange.*" with sub-packages like the "yhoo" or "yahoo".

**Comment by otaviojava** [comment]
I did the first step on yahoo implementation and I did some tests.
Is there any way to find out from date?

**Comment by keilw** [comment]
Please as a next step fix the package name, a library here must not be "org.javamoney.moneta.internal.convert.yahoo". See above, "org.javamoney.lib.exchange.yahoo" ("convert" was also OK, but you picked the module name so better use "exchange" in this context only;-) or "org.javamoney.exchange.yahoo" but not "moneta" or any other pre-defined existing package namespaces.

**Comment by atsticks** [comment]
@otaviojava  As of now all tests accessing real yahoo/frc rates do actually fail. Can you have a look at it, please?

**Comment by keilw** [comment]
Do the APIs still exist at Yahoo? ;-)

**Comment by otaviojava** [comment]
@atsticks yes, I can do it

**Comment by keilw** [comment]
Please do. @atsticks By when would you envision Library 0.9 (would not call it 1.0 yet, maybe based on the next RI updates ;-) ) to be released or is there a downstream dependent waiting for it?

**Comment by atsticks** [comment]
If exchange is ready and you think also cdi annotations are fine for you, I
would release them. This would allow Apache Fineract to use it and also
helping improving it...

Am 12.02.2017 4:44 PM schrieb "Werner Keil" <notifications@github.com>:

Please do. @atsticks <https://github.com/atsticks> By when would you
envision Library 0.9 (would not call it 1.0 yet, maybe based on the next RI
updates ;-) ) to be released or is there a downstream dependent waiting for
it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JavaMoney/javamoney-lib/issues/22#issuecomment-279226847>,
or mute the thread

**Comment by keilw** [comment]
If there is no requirement on the signature to sign those (like for the JSR earlier), I can publish them to Bintray.

**Comment by atsticks** [comment]
Fixed impl.
