### ISSUE TITLE
Unable to build due to moneta.core 1.2 jar is missing

### ISSUE THREAD

**Issue by seshalh** [JavaMoney/javamoney-lib#44]
I am unable to build javamoney-lib and its dependency libs due to missing to download moneta.core 1.2 version jar file.
Please suggest the alternate version of it. I tried with moneta 1,1 & 1.0 version and not success

**Comment by keilw** [comment]
This is due to https://github.com/JavaMoney/jsr354-ri/issues/186. Will keep it open to track but no action is  needed here AFAIK.

**Comment by awasum** [comment]
Using the `mvn install -Dmaven.test.skip=true` fails to build. Is there another way to fix this? This might be as a result of the recent updates to the code base.

**Comment by keilw** [comment]
As long as the dependency is not available either on Bintray or MavenCentral  it won't work.

**Comment by awasum** [comment]
Ok...thanks. Am waiting.

**Comment by keilw** [comment]
Fixed, although had to reopen https://github.com/JavaMoney/jsr354-ri/issues/186 because the Moneta POM refers to the wrong Money-API version (1.0.2-SNAPSHOT instead of final) this works, but all builds have to run Java 9. After fixing the Travis file it works and this POM uses the correct API version, so it'll override the problem in Moneta 1.2.
